In [1]:
# -- 2.1.1 --

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [3]:
df = pd.read_csv("../../course_assignments/homework9/solar_system.csv")
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [4]:
print("shape before transposing:", df.shape)

df = df.set_index("Attribute").T
print("shape after transposing:", df.shape)

shape before transposing: (20, 11)
shape after transposing: (10, 20)

Before transposing, the DataFrame had 20 rows and 11 columns. After transposing, the DataFrame had 10 rows and 20 columns.

In [5]:
df = pd.read_csv("../../course_assignments/homework9/solar_system.csv")

print("original shape:", df.shape)

df = df.set_index("Attribute")
print("after set_index('Attribute'):", df.shape)

df = df.T
print("after transpose:", df.shape)

df.index.name = "Planet"
print("after naming index:", df.shape)

df.reset_index(inplace = True)
print("after reset_index:", df.shape)

df.columns.name = None
print("after removing columns name:", df.shape)

original shape: (20, 11)
after set_index('Attribute'): (20, 10)
after transpose: (10, 20)
after naming index: (10, 20)
after reset_index: (10, 21)
after removing columns name: (10, 21)

df.set_index("Attribute") makes the Attribute column become the index of the DataFrame. The shape changes from (20,11) to (20,10) because "Attribute" is no longer a regular column.

df.T transposes the DataFrame, which means that the rows and columns switch. Then, each row represents a planet instead of an attribute. 

df.index.name = "Planet" gives the index the name "Planet". This doesn't change the shape.

df.reset_index(inplace=True) turns the planet index into a regular column called "Planet". This changes the shape from (10,20) to (10,21)

df.columns.name = None removes the extra column index name from the DataFrame. This makes the table cleaner and doesn't change the shape.

The new shape is not (11,20) because the "Attribute" column was used as the index before transposing. After transposing, the planet names are stored in the index, not as a normal column. Then reset_index() adds the planet names back as a new column called "Planet", so the final DataFrame has 21 columns.

In [6]:
print(df.columns.tolist())

['Planet', 'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

There are 16 columns with units:
'Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)'

There are 5 columns without units:
'Planet', 'Orbital Eccentricity', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?'

In [7]:
df

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [8]:
# -- 2.1.2 --

In [9]:
df.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [10]:
for col in df.columns:
    print(df[col].apply(type).value_counts())
    print()

Planet
<class 'str'>    10
Name: count, dtype: int64

Mass (10^24kg)
<class 'str'>    10
Name: count, dtype: int64

Diameter (km)
<class 'str'>    10
Name: count, dtype: int64

Density (kg/m^3)
<class 'str'>    10
Name: count, dtype: int64

Gravity (m/s^2)
<class 'str'>    10
Name: count, dtype: int64

Escape Velocity (km/s)
<class 'str'>    10
Name: count, dtype: int64

Rotation Period (hours)
<class 'str'>    10
Name: count, dtype: int64

Length of Day (hours)
<class 'str'>    10
Name: count, dtype: int64

Distance from Sun (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Perihelion (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Aphelion (10^6 km)
<class 'str'>    10
Name: count, dtype: int64

Orbital Period (days)
<class 'str'>    10
Name: count, dtype: int64

Orbital Velocity (km/s)
<class 'str'>    10
Name: count, dtype: int64

Orbital Inclination (deg)
<class 'str'>    10
Name: count, dtype: int64

Orbital Eccentricity
<class 'str'>    10
Name: count, dtype: int64

Obliquity to Orbit (deg)
<class 'str'>    10
Name: count, dtype: int64

Mean Temperature (C)
<class 'str'>    10
Name: count, dtype: int64

Surface Pressure (bars)
<class 'str'>    10
Name: count, dtype: int64

Number of Moons
<class 'str'>    10
Name: count, dtype: int64

Ring System?
<class 'str'>    10
Name: count, dtype: int64

Global Magnetic Field?
<class 'str'>    10
Name: count, dtype: int64

(a)
The actual values are strings, even though many values look like numbers.

(b)
This is a problem becuase Python treats them as text instead of numbers. This means calculations, plotting, averages, and unit conversions will not work correctly.

In [11]:
# -- 2.1.3 --

In [12]:
for col in df.columns:
    if col not in ["Planet", "Ring System?", "Global Magnetic Field?"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [13]:
df.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

(a)
The three different data types are object, float 64, and int64

(b)
Object means the columns contains text or non-numeric values. 
Float64 means the column contains decimal numbers. 
Int64 means the column contains whole numbers.

(c)
The columns that are still object are "Planet", "Ring System?", and "Global Magnetic Field?". It's becuase they contains names or yes/no text values instead of numbers.

In [14]:
# -- 2.2 --

In [15]:
def attach_units(old_col, new_col, unit):
    new_values = []
    
    for val in df[old_col]:
        new_values.append(val * unit)
    
    df[old_col] = new_values
    df.rename(columns={old_col: new_col}, inplace=True)

In [16]:
attach_units("Mass (10^24kg)", "Mass (kg)", 1e24 * u.kg)

In [17]:
print(df["Mass (kg)"])

0                   3.3e+23 kg
1                  4.87e+24 kg
2     5.969999999999999e+24 kg
3                   7.3e+22 kg
4                  6.42e+23 kg
5                 1.898e+27 kg
6                  5.68e+26 kg
7                  8.68e+25 kg
8    1.0199999999999999e+26 kg
9                   1.3e+22 kg
Name: Mass (kg), dtype: object

In [18]:
# -- 2.3.1 --

In [19]:
semi_major_axis = []

for i in range(len(df)):
    value = (df["Perihelion (10^6 km)"][i] + df["Aphelion (10^6 km)"][i]) / 2
    semi_major_axis.append(value * 1e6 * u.km)

In [20]:
aphelion_index = df.columns.get_loc("Aphelion (10^6 km)")

df.insert(aphelion_index + 1, "semi-major axis (km)", semi_major_axis)

In [21]:
print(df.columns.tolist())

['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'semi-major axis (km)', 'Orbital Period (days)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

In [22]:
print(df["semi-major axis (km)"])

0      57900000.0 km
1     108200000.0 km
2     149600000.0 km
3        384500.0 km
4     228000000.0 km
5     778500000.0 km
6    1432050000.0 km
7    2867050000.0 km
8    4515000000.0 km
9    5906350000.0 km
Name: semi-major axis (km), dtype: object

In [23]:
# -- 2.3.2 --

In [24]:
orbital_period_years = []

for val in df["Orbital Period (days)"]:
    orbital_period_years.append((val * u.day).to(u.year))
    
df["Orbital Period (days)"] = orbital_period_years
df.rename(columns={"Orbital Period (days)": "Orbital Period (years)"}, inplace=True)

In [25]:
print(df.columns.tolist())

['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Distance from Sun (10^6 km)', 'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'semi-major axis (km)', 'Orbital Period (years)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?']

In [26]:
print(df["Orbital Period (years)"])

0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object

In [27]:
earth_period = df.loc[df["Planet"] == "Earth", "Orbital Period (years)"].iloc[0]
print(f"Earth's orbital period is {earth_period.value:.4f} years")

Earth's orbital period is 0.9999 years

In [28]:
# -- 2.3.3 --

Define AU: the average distance between Earth and the Sun.

In [29]:
print(const.au)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [30]:
print(const.au.to(u.km))

149597870.70000002 km

In [31]:
df["Diameter (AU)"] = [(val * u.km).to(u.AU) for val in df["Diameter (km)"]]

df["Distance from Sun (AU)"] = [(val * 1e6 * u.km).to(u.AU) for val in df["Distance from Sun (10^6 km)"]]

df["Perihelion (AU)"] = [(val * 1e6 * u.km).to(u.AU) for val in df["Perihelion (10^6 km)"]]

df["Aphelion (AU)"] = [(val * 1e6 * u.km).to(u.AU) for val in df["Aphelion (10^6 km)"]]

df["semi-major axis (AU)"] = [val.to(u.AU) for val in df["semi-major axis (km)"]]

df = df.drop(columns=[
    "Diameter (km)",
    "Distance from Sun (10^6 km)",
    "Perihelion (10^6 km)",
    "Aphelion (10^6 km)",
    "semi-major axis (km)"
])

In [32]:
print(df.columns.tolist())

['Planet', 'Mass (kg)', 'Density (kg/m^3)', 'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)', 'Length of Day (hours)', 'Orbital Period (years)', 'Orbital Velocity (km/s)', 'Orbital Inclination (deg)', 'Orbital Eccentricity', 'Obliquity to Orbit (deg)', 'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons', 'Ring System?', 'Global Magnetic Field?', 'Diameter (AU)', 'Distance from Sun (AU)', 'Perihelion (AU)', 'Aphelion (AU)', 'semi-major axis (AU)']

In [33]:
print(df.loc[df["Planet"] == "Earth", [
    "Diameter (AU)",
    "Distance from Sun (AU)",
    "Perihelion (AU)",
    "Aphelion (AU)",
    "semi-major axis (AU)"
]])

              Diameter (AU) Distance from Sun (AU)        Perihelion (AU)  \
2  8.526859333165629e-05 AU  1.0000142334913595 AU  0.9833027656856883 AU

           Aphelion (AU)   semi-major axis (AU)
2  1.0167257012970305 AU  1.0000142334913595 AU

In [34]:
# -- 2.4 --

In [35]:
df.to_csv("units.csv", index=False)